// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlgtSb3LhscGHlNoXpRB-cUBzEoWZdIzA',
    appId: '1:85011720124:web:1dd98e30ea1ca4afe46db9',
    messagingSenderId: '85011720124',
    projectId: 'smart-hydroponic-8529f',
    authDomain: 'smart-hydroponic-8529f.firebaseapp.com',
    databaseURL: 'https://smart-hydroponic-8529f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-hydroponic-8529f.firebasestorage.app',
    measurementId: 'G-6KBB0KQD3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg_D3UX7XhSHYNd-Buas5TVRmhErmId9I',
    appId: '1:85011720124:android:a7d5dc1bbf70fc9be46db9',
    messagingSenderId: '85011720124',
    projectId: 'smart-hydroponic-8529f',
    databaseURL: 'https://smart-hydroponic-8529f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-hydroponic-8529f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC8z55rsqMUY6WKX3PGRnxckvvkdpUQJA',
    appId: '1:85011720124:ios:676b006c0b9ca205e46db9',
    messagingSenderId: '85011720124',
    projectId: 'smart-hydroponic-8529f',
    databaseURL: 'https://smart-hydroponic-8529f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-hydroponic-8529f.firebasestorage.app',
    iosBundleId: 'com.example.aquagrowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC8z55rsqMUY6WKX3PGRnxckvvkdpUQJA',
    appId: '1:85011720124:ios:676b006c0b9ca205e46db9',
    messagingSenderId: '85011720124',
    projectId: 'smart-hydroponic-8529f',
    databaseURL: 'https://smart-hydroponic-8529f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-hydroponic-8529f.firebasestorage.app',
    iosBundleId: 'com.example.aquagrowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlgtSb3LhscGHlNoXpRB-cUBzEoWZdIzA',
    appId: '1:85011720124:web:1dd98e30ea1ca4afe46db9',
    messagingSenderId: '85011720124',
    projectId: 'smart-hydroponic-8529f',
    authDomain: 'smart-hydroponic-8529f.firebaseapp.com',
    databaseURL: 'https://smart-hydroponic-8529f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-hydroponic-8529f.firebasestorage.app',
    measurementId: 'G-6KBB0KQD3W',
  );

}